language: android
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - lynx
  sonarcloud:
    organization: "netodevel-github" 
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-android-m2repository
  - extra-android-support

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install: chmod +x publish.sh
script: 
    - sh publish.sh
#    - sonar-scanner

